development:
  adapter: postgresql
  encoding: unicode
  database: blog_app_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: blog_app_test
  pool: 5
  username:
  password:
